#"window.dynamic_title" = true
#"window.opacity" = 1.0

[window]
opacity=1.0
#decorations = "None" # Removes topbar
#decorations = "Full"

[colors]
draw_bold_text_with_bright_colors = true

[colors.bright]
black = "#4C566A"
blue = "#81A1C1"
cyan = "#8FBCBB"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#ECEFF4"
yellow = "#EBCB8B"

[colors.normal]
black = "#3B4252"
blue = "#81A1C1"
cyan = "#88C0D0"
green = "#A3BE8C"
magenta = "#B48EAD"
red = "#BF616A"
white = "#E5E9F0"
yellow = "#EBCB8B"

[colors.primary]
background = "#2E3440"
foreground = "#D8DEE9"

[font]
size = 13.0

[font.bold]
family = "JetBrainsMono NF"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono NF"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono NF"
style = "Italic"

[font.normal]
family = "JetBrainsMono NF"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BF"
key = "Right"
mods = "Control"

[[keyboard.bindings]]
chars = "\u001BB"
key = "Left"
mods = "Control"

[general]
live_config_reload = true

[scrolling]
history = 10000
multiplier = 10

[selection]
save_to_clipboard = true
semantic_escape_chars = """,│`|:"' ()[]{}<>"""

[window.padding]
x = 14
y = 4

[keyboard]
